/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.neko.demo;

import org.junit.Test;
import static org.junit.Assert.*;

public class MainTest {
    @Test
    public void test() {
        assertTrue("should return 'true'", true);
    }
}
